
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.testlang.parser;

import com.testlang.ast.*;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\043\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\002\004\000\002\002\003\000\002\003\006" +
    "\000\002\004\004\000\002\004\003\000\002\005\006\000" +
    "\002\005\007\000\002\006\004\000\002\006\003\000\002" +
    "\007\007\000\002\007\007\000\002\010\004\000\002\010" +
    "\003\000\002\011\007\000\002\012\004\000\002\012\003" +
    "\000\002\013\003\000\002\013\003\000\002\014\005\000" +
    "\002\014\005\000\002\014\010\000\002\014\010\000\002" +
    "\015\003\000\002\015\002\000\002\016\004\000\002\016" +
    "\003\000\002\017\007\000\002\017\006\000\002\020\007" +
    "\000\002\020\010\000\002\020\010\000\002\020\007" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\134\000\010\004\012\007\011\010\007\001\002\000" +
    "\004\002\136\001\002\000\006\007\011\010\007\001\002" +
    "\000\006\002\ufff2\010\ufff2\001\002\000\004\025\044\001" +
    "\002\000\006\007\011\010\007\001\002\000\004\025\034" +
    "\001\002\000\004\021\016\001\002\000\006\007\ufff6\010" +
    "\ufff6\001\002\000\006\002\ufffd\010\007\001\002\000\006" +
    "\002\ufff3\010\ufff3\001\002\000\006\005\022\006\021\001" +
    "\002\000\010\005\ufffa\006\ufffa\022\ufffa\001\002\000\010" +
    "\005\022\006\021\022\033\001\002\000\004\026\026\001" +
    "\002\000\004\023\023\001\002\000\004\026\024\001\002" +
    "\000\004\024\025\001\002\000\010\005\ufff9\006\ufff9\022" +
    "\ufff9\001\002\000\004\023\027\001\002\000\004\026\030" +
    "\001\002\000\004\024\031\001\002\000\010\005\ufff8\006" +
    "\ufff8\022\ufff8\001\002\000\010\005\ufffb\006\ufffb\022\ufffb" +
    "\001\002\000\006\007\ufffc\010\ufffc\001\002\000\004\023" +
    "\035\001\002\000\006\026\036\027\037\001\002\000\004" +
    "\024\041\001\002\000\004\024\040\001\002\000\006\007" +
    "\ufff4\010\ufff4\001\002\000\006\007\ufff5\010\ufff5\001\002" +
    "\000\006\002\ufffe\010\007\001\002\000\006\007\ufff7\010" +
    "\ufff7\001\002\000\004\021\045\001\002\000\014\011\056" +
    "\012\055\013\050\014\053\015\052\001\002\000\016\011" +
    "\uffee\012\uffee\013\uffee\014\uffee\015\uffee\022\uffee\001\002" +
    "\000\016\011\uffed\012\uffed\013\uffed\014\uffed\015\uffed\022" +
    "\uffed\001\002\000\004\026\126\001\002\000\016\011\uffef" +
    "\012\uffef\013\uffef\014\uffef\015\uffef\022\uffef\001\002\000" +
    "\010\006\110\016\106\017\107\001\002\000\004\026\104" +
    "\001\002\000\016\011\056\012\055\013\050\014\053\015" +
    "\052\022\103\001\002\000\004\026\061\001\002\000\004" +
    "\026\057\001\002\000\004\024\060\001\002\000\016\011" +
    "\uffec\012\uffec\013\uffec\014\uffec\015\uffec\022\uffec\001\002" +
    "\000\004\021\062\001\002\000\010\006\067\017\066\022" +
    "\uffe7\001\002\000\010\006\067\017\066\022\uffe8\001\002" +
    "\000\010\006\uffe5\017\uffe5\022\uffe5\001\002\000\004\022" +
    "\077\001\002\000\004\023\074\001\002\000\004\026\070" +
    "\001\002\000\004\023\071\001\002\000\004\026\072\001" +
    "\002\000\004\024\073\001\002\000\010\006\uffe4\017\uffe4" +
    "\022\uffe4\001\002\000\004\026\075\001\002\000\004\024" +
    "\076\001\002\000\010\006\uffe3\017\uffe3\022\uffe3\001\002" +
    "\000\004\024\100\001\002\000\016\011\uffea\012\uffea\013" +
    "\uffea\014\uffea\015\uffea\022\uffea\001\002\000\010\006\uffe6" +
    "\017\uffe6\022\uffe6\001\002\000\016\011\ufff0\012\ufff0\013" +
    "\ufff0\014\ufff0\015\ufff0\022\ufff0\001\002\000\006\002\ufff1" +
    "\010\ufff1\001\002\000\004\024\105\001\002\000\016\011" +
    "\uffeb\012\uffeb\013\uffeb\014\uffeb\015\uffeb\022\uffeb\001\002" +
    "\000\004\023\123\001\002\000\004\020\120\001\002\000" +
    "\004\026\111\001\002\000\006\020\112\023\113\001\002" +
    "\000\004\026\116\001\002\000\004\026\114\001\002\000" +
    "\004\024\115\001\002\000\016\011\uffe1\012\uffe1\013\uffe1" +
    "\014\uffe1\015\uffe1\022\uffe1\001\002\000\004\024\117\001" +
    "\002\000\016\011\uffe0\012\uffe0\013\uffe0\014\uffe0\015\uffe0" +
    "\022\uffe0\001\002\000\004\026\121\001\002\000\004\024" +
    "\122\001\002\000\016\011\uffdf\012\uffdf\013\uffdf\014\uffdf" +
    "\015\uffdf\022\uffdf\001\002\000\004\027\124\001\002\000" +
    "\004\024\125\001\002\000\016\011\uffe2\012\uffe2\013\uffe2" +
    "\014\uffe2\015\uffe2\022\uffe2\001\002\000\004\021\127\001" +
    "\002\000\010\006\067\017\066\022\uffe7\001\002\000\004" +
    "\022\131\001\002\000\004\024\132\001\002\000\016\011" +
    "\uffe9\012\uffe9\013\uffe9\014\uffe9\015\uffe9\022\uffe9\001\002" +
    "\000\006\007\011\010\007\001\002\000\006\002\uffff\010" +
    "\007\001\002\000\006\002\000\010\007\001\002\000\004" +
    "\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\134\000\016\002\003\003\004\006\007\007\012\010" +
    "\013\011\005\001\001\000\002\001\001\000\012\006\132" +
    "\007\012\010\133\011\005\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\007\042\010\041\011\005\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\011\014\001\001\000\002\001\001\000\006\004\017" +
    "\005\016\001\001\000\002\001\001\000\004\005\031\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\014\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\012\053\013\050\014\045" +
    "\020\046\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\013\101\014\045\020\046\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\015\064\016\062\017" +
    "\063\001\001\000\004\017\100\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\015\127\016\062\017" +
    "\063\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\007\042\010\134\011\005\001\001\000" +
    "\004\011\014\001\001\000\004\011\014\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void report_error(String message, Object info) {
        StringBuilder m = new StringBuilder("Syntax error");
        if (info instanceof java_cup.runtime.Symbol) {
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
            if (s.left >= 0) {
                m.append(" at line ").append(s.left + 1);
                if (s.right >= 0) {
                    m.append(", column ").append(s.right + 1);
                }
            }
        }
        m.append(": ").append(message);
        System.err.println(m);
    }

    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Program ::= Config VariableDeclarations Tests 
            {
              Object RESULT =null;
		int configleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int configright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object config = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int varsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object vars = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int testsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int testsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object tests = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Program((Config)config, (VariableDeclarations)vars, (Tests)tests); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Program ::= Config Tests 
            {
              Object RESULT =null;
		int configleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int configright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object config = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int testsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int testsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object tests = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Program((Config)config, new VariableDeclarations(), (Tests)tests); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Program ::= VariableDeclarations Tests 
            {
              Object RESULT =null;
		int varsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object vars = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int testsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int testsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object tests = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Program(null, (VariableDeclarations)vars, (Tests)tests); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Program ::= Tests 
            {
              Object RESULT =null;
		int testsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int testsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object tests = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Program(null, new VariableDeclarations(), (Tests)tests); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Config ::= CONFIG LBRACE ConfigEntries RBRACE 
            {
              Object RESULT =null;
		int entriesleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int entriesright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object entries = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Config((ConfigEntries)entries); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Config",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // ConfigEntries ::= ConfigEntries ConfigEntry 
            {
              Object RESULT =null;
		int entriesleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int entriesright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object entries = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int entryleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int entryright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object entry = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 ((ConfigEntries)entries).addEntry((ConfigEntry)entry); RESULT = entries; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConfigEntries",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // ConfigEntries ::= ConfigEntry 
            {
              Object RESULT =null;
		int entryleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int entryright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object entry = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 ConfigEntries entries = new ConfigEntries(); entries.addEntry((ConfigEntry)entry); RESULT = entries; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConfigEntries",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // ConfigEntry ::= BASE_URL EQUALS STRING SEMICOLON 
            {
              Object RESULT =null;
		int urlleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int urlright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String url = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new ConfigEntry("base_url", (String)url); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConfigEntry",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // ConfigEntry ::= HEADER STRING EQUALS STRING SEMICOLON 
            {
              Object RESULT =null;
		int keyleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int keyright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String key = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new ConfigEntry("header", (String)key, (String)value); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ConfigEntry",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // VariableDeclarations ::= VariableDeclarations VariableDeclaration 
            {
              Object RESULT =null;
		int declsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int declsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object decls = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int declleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int declright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object decl = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 ((VariableDeclarations)decls).addDeclaration((VariableDeclaration)decl); RESULT = decls; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("VariableDeclarations",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // VariableDeclarations ::= VariableDeclaration 
            {
              Object RESULT =null;
		int declleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int declright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object decl = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 VariableDeclarations decls = new VariableDeclarations(); decls.addDeclaration((VariableDeclaration)decl); RESULT = decls; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("VariableDeclarations",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // VariableDeclaration ::= LET IDENTIFIER EQUALS STRING SEMICOLON 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new VariableDeclaration((String)name, (String)value); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("VariableDeclaration",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // VariableDeclaration ::= LET IDENTIFIER EQUALS NUMBER SEMICOLON 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer value = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new VariableDeclaration((String)name, (Integer)value); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("VariableDeclaration",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Tests ::= Tests TestBlock 
            {
              Object RESULT =null;
		int testsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int testsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object tests = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int testleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int testright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object test = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 ((Tests)tests).addTest((TestBlock)test); RESULT = tests; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Tests",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Tests ::= TestBlock 
            {
              Object RESULT =null;
		int testleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int testright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object test = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 Tests tests = new Tests(); tests.addTest((TestBlock)test); RESULT = tests; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Tests",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // TestBlock ::= TEST IDENTIFIER LBRACE TestSteps RBRACE 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int stepsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int stepsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object steps = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new TestBlock((String)name, (TestSteps)steps); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TestBlock",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // TestSteps ::= TestSteps TestStep 
            {
              Object RESULT =null;
		int stepsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int stepsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object steps = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int stepleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int stepright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object step = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 ((TestSteps)steps).addStep((TestStep)step); RESULT = steps; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TestSteps",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // TestSteps ::= TestStep 
            {
              Object RESULT =null;
		int stepleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int stepright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object step = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 TestSteps testSteps = new TestSteps(); testSteps.addStep((TestStep)step); RESULT = testSteps; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TestSteps",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // TestStep ::= Request 
            {
              Object RESULT =null;
		int requestleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int requestright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object request = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new TestStep((Request)request); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TestStep",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // TestStep ::= Assertion 
            {
              Object RESULT =null;
		int assertionleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int assertionright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object assertion = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new TestStep((Assertion)assertion); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("TestStep",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Request ::= GET STRING SEMICOLON 
            {
              Object RESULT =null;
		int pathleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pathright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String path = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Request("GET", (String)path, null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Request",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Request ::= DELETE STRING SEMICOLON 
            {
              Object RESULT =null;
		int pathleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pathright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String path = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Request("DELETE", (String)path, null); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Request",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Request ::= POST STRING LBRACE RequestBlock RBRACE SEMICOLON 
            {
              Object RESULT =null;
		int pathleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int pathright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String path = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int blockleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int blockright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object block = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = new Request("POST", (String)path, (RequestBlock)block); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Request",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Request ::= PUT STRING LBRACE RequestBlock RBRACE SEMICOLON 
            {
              Object RESULT =null;
		int pathleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int pathright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String path = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int blockleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int blockright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object block = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = new Request("PUT", (String)path, (RequestBlock)block); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Request",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // RequestBlock ::= RequestEntries 
            {
              Object RESULT =null;
		int entriesleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int entriesright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object entries = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new RequestBlock((RequestEntries)entries); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("RequestBlock",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // RequestBlock ::= 
            {
              Object RESULT =null;
		 RESULT = new RequestBlock(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("RequestBlock",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // RequestEntries ::= RequestEntries RequestEntry 
            {
              Object RESULT =null;
		int entriesleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int entriesright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object entries = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int itemleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int itemright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object item = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 ((RequestEntries)entries).addEntry((RequestEntry)item); RESULT = entries; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("RequestEntries",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // RequestEntries ::= RequestEntry 
            {
              Object RESULT =null;
		int itemleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int itemright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object item = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RequestEntries entries = new RequestEntries(); entries.addEntry((RequestEntry)item); RESULT = entries; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("RequestEntries",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // RequestEntry ::= HEADER STRING EQUALS STRING SEMICOLON 
            {
              Object RESULT =null;
		int keyleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int keyright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String key = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new RequestEntry("header", (String)key, (String)value); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("RequestEntry",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // RequestEntry ::= BODY EQUALS STRING SEMICOLON 
            {
              Object RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new RequestEntry("body", (String)value); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("RequestEntry",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // Assertion ::= EXPECT STATUS EQUALS NUMBER SEMICOLON 
            {
              Object RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Integer value = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Assertion("status", (Integer)value); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Assertion",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // Assertion ::= EXPECT HEADER STRING EQUALS STRING SEMICOLON 
            {
              Object RESULT =null;
		int keyleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int keyright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String key = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Assertion("header_equals", (String)key, (String)value); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Assertion",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Assertion ::= EXPECT HEADER STRING CONTAINS STRING SEMICOLON 
            {
              Object RESULT =null;
		int keyleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int keyright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String key = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Assertion("header_contains", (String)key, (String)value); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Assertion",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // Assertion ::= EXPECT BODY CONTAINS STRING SEMICOLON 
            {
              Object RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String value = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Assertion("body_contains", (String)value); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Assertion",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
